fix: CI中新增对Docusaurus build的报错

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -83,7 +83,18 @@ jobs:
       
       - name: Build site
         run: sed -i 's/CI_BUILED_BASEURL/\/puki\/${{ steps.info.outputs.build-tag }}\/app\/site\//' ./site/docusaurus.config.js && cd site && yarn
-      
+
+      - name: Docusaurus build post message
+        if: ${{ failure() }}
+        run: |
+          curl \
+          -X POST \
+          -H "Accept: application/vnd.github.v3+json" \
+          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" \
+          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
+          -d '{"body":'"$(printf "**❌ Docusaurus Build failed**\n" | jq  -aRs .)"'}' \
+          && exit 1
+        
       - name: Fontend code style check
         run: cd app && yarn prettier:check > /tmp/prettierout 2>&1
 
